# Generated by Django 2.2.2 on 2019-06-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('payload', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('headline', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=1500)),
            ],
        ),
    ]
