# Generated by Django 2.2.2 on 2019-06-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_news', '0002_auto_20190618_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launches',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
