# Generated by Django 2.2.2 on 2019-06-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_news', '0004_auto_20190618_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
    ]
