# Generated by Django 2.2.2 on 2019-06-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_news', '0005_remove_news_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='headline',
            new_name='name',
        ),
    ]
